### PR TITLE
fixes needed for CC8: use std::isnan

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
FYI @andrius-k and @jfernan2

**Comment by andrius-k** [comment]
Tested locally and no issues were observed - merging!

**Comment by smuzaffar** [comment]
can you please provide a new tag e..g 1.1.0?

**Comment by andrius-k** [comment]
Hi @smuzaffar, I created a release 1.0.1: https://github.com/cms-DQM/dqmgui/releases/tag/1.0.1

Looks like the deployment procedure of the new DQM GUI is gaining shape! I still have a few questions remaining that I'd like to ask you:

* What is the way DQM GUI code will make its way to the Online P5 machines?
   * In Offline, the repository can simply be cloned, so it's not a problem.
* What is the preferred way to handle the python dependencies declared here: https://github.com/cms-DQM/dqmgui/blob/master/python/requirements.txt

Regards,
Andrius

**Comment by smuzaffar** [comment]
> What is the way DQM GUI code will make its way to the Online P5 machines?

P5 system admins ( who install cmssw releases on P5) already clone cms offline repository on P5 systems. So you should check with them how to install dqmgui. They can install dqmqui release the same way they are install cmssw releases ( I think it is via puppet using cmspkg provider).

> What is the preferred way to handle the python dependencies declared

Just make sure that the dependency mentioned https://github.com/cms-DQM/dqmgui/blob/master/python/requirements.txt is also available https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/dqmgui.tmpl#L10 

DQM team should be responsible for providing changes for https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/dqmgui.tmpl file e.g. whenever yuou have a new dqmgui version or updated dependency then you should open a PR for cmsdist/dqmgui.tmpl

**Comment by andrius-k** [comment]
Perfect, thanks a lot!

**Pull request merged**
